"""add json_storage_id to report_version; make pdf_storage_id nullable

Revision ID: 35e3a21469fb
Revises: 588a83d028a1
Create Date: 2025-09-16 17:22:43.010535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e3a21469fb'
down_revision: Union[str, Sequence[str], None] = '588a83d028a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_version', sa.Column('json_storage_id', sa.Uuid(), nullable=True))
    op.alter_column('report_version', 'pdf_storage_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'report_version', 'storage_object', ['json_storage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report_version', type_='foreignkey')
    op.alter_column('report_version', 'pdf_storage_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('report_version', 'json_storage_id')
    # ### end Alembic commands ###
