"""add_username_field_to_user

Revision ID: 588a83d028a1
Revises: 69da96b8aea7
Create Date: 2025-08-27 21:58:09.863511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588a83d028a1'
down_revision: Union[str, Sequence[str], None] = '69da96b8aea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('username', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_app_user_username'), 'app_user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_user_username'), table_name='app_user')
    op.drop_column('app_user', 'username')
    # ### end Alembic commands ###
