"""add new features: events, billing catalog, invitations, user profiles

Revision ID: 6965b748777e
Revises: b1e053ebeb94
Create Date: 2025-11-06 21:47:17.362092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6965b748777e'
down_revision: Union[str, Sequence[str], None] = 'b1e053ebeb94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_catalog',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('service_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('service_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_token',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_token_token'), 'password_reset_token', ['token'], unique=True)
    op.create_table('user_invitation',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'PATHOLOGIST', 'LAB_TECH', 'ASSISTANT', 'BILLING', 'VIEWER', name='userrole', create_type=False), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_invitation_email'), 'user_invitation', ['email'], unique=False)
    op.create_index(op.f('ix_user_invitation_token'), 'user_invitation', ['token'], unique=True)
    # Create EventType enum
    event_type_enum = postgresql.ENUM('ORDER_CREATED', 'SAMPLE_RECEIVED', 'SAMPLE_PREPARED', 'IMAGE_UPLOADED', 'REPORT_CREATED', 'REPORT_SUBMITTED', 'REPORT_APPROVED', 'REPORT_CHANGES_REQUESTED', 'REPORT_SIGNED', 'INVOICE_CREATED', 'PAYMENT_RECEIVED', 'ORDER_DELIVERED', 'ORDER_CANCELLED', 'STATUS_CHANGED', 'NOTE_ADDED', name='eventtype')
    event_type_enum.create(op.get_bind())
    op.create_table('case_event',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', postgresql.ENUM('ORDER_CREATED', 'SAMPLE_RECEIVED', 'SAMPLE_PREPARED', 'IMAGE_UPLOADED', 'REPORT_CREATED', 'REPORT_SUBMITTED', 'REPORT_APPROVED', 'REPORT_CHANGES_REQUESTED', 'REPORT_SIGNED', 'INVOICE_CREATED', 'PAYMENT_RECEIVED', 'ORDER_DELIVERED', 'ORDER_CANCELLED', 'STATUS_CHANGED', 'NOTE_ADDED', name='eventtype', create_type=False), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['lab_order.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_item',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service_catalog.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('app_user', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('tenant', sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))

    op.add_column('tenant', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'is_active')
    op.drop_column('tenant', 'logo_url')
    op.drop_column('app_user', 'avatar_url')
    op.drop_table('invoice_item')
    op.drop_table('case_event')
    # Drop EventType enum
    event_type_enum = postgresql.ENUM(name='eventtype')
    event_type_enum.drop(op.get_bind())
    op.drop_index(op.f('ix_user_invitation_token'), table_name='user_invitation')
    op.drop_index(op.f('ix_user_invitation_email'), table_name='user_invitation')
    op.drop_table('user_invitation')
    op.drop_index(op.f('ix_password_reset_token_token'), table_name='password_reset_token')
    op.drop_table('password_reset_token')
    op.drop_table('service_catalog')
    # ### end Alembic commands ###
