"""add signature fields to report_version

Revision ID: b1e053ebeb94
Revises: 35e3a21469fb
Create Date: 2025-11-06 20:07:18.379040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e053ebeb94'
down_revision: Union[str, Sequence[str], None] = '35e3a21469fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_version', sa.Column('signed_by', sa.Uuid(), nullable=True))
    op.add_column('report_version', sa.Column('signed_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'report_version', 'app_user', ['signed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report_version', type_='foreignkey')
    op.drop_column('report_version', 'signed_at')
    op.drop_column('report_version', 'signed_by')
    # ### end Alembic commands ###
