"""Add hashed_password to app_user

Revision ID: f45e096206ac
Revises: d34b82b6375e
Create Date: 2025-08-17 16:22:33.379530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f45e096206ac'
down_revision: Union[str, Sequence[str], None] = 'd34b82b6375e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'hashed_password')
    # ### end Alembic commands ###
