from enum import Enum

class UserRole(str, Enum):
    ADMIN = "admin"
    PATHOLOGIST = "pathologist"
    LAB_TECH = "lab_tech"
    ASSISTANT = "assistant"
    BILLING = "billing"
    VIEWER = "viewer"

class OrderStatus(str, Enum):
    RECEIVED = "RECEIVED"
    PROCESSING = "PROCESSING"
    DIAGNOSIS = "DIAGNOSIS"
    REVIEW = "REVIEW"
    RELEASED = "RELEASED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"

class SampleType(str, Enum):
    SANGRE = "SANGRE"
    BIOPSIA = "BIOPSIA"
    LAMINILLA = "LAMINILLA"
    TEJIDO = "TEJIDO"
    OTRO = "OTRO"

class ReportStatus(str, Enum):
    DRAFT = "DRAFT"
    IN_REVIEW = "IN_REVIEW"
    APPROVED = "APPROVED"
    PUBLISHED = "PUBLISHED"
    RETRACTED = "RETRACTED"

class PaymentStatus(str, Enum):
    PENDING = "PENDING"
    PAID = "PAID"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"
    PARTIAL = "PARTIAL"

class EventType(str, Enum):
    ORDER_CREATED = "ORDER_CREATED"
    SAMPLE_RECEIVED = "SAMPLE_RECEIVED"
    SAMPLE_PREPARED = "SAMPLE_PREPARED"
    IMAGE_UPLOADED = "IMAGE_UPLOADED"
    REPORT_CREATED = "REPORT_CREATED"
    REPORT_SUBMITTED = "REPORT_SUBMITTED"
    REPORT_APPROVED = "REPORT_APPROVED"
    REPORT_CHANGES_REQUESTED = "REPORT_CHANGES_REQUESTED"
    REPORT_SIGNED = "REPORT_SIGNED"
    INVOICE_CREATED = "INVOICE_CREATED"
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED"
    ORDER_DELIVERED = "ORDER_DELIVERED"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    STATUS_CHANGED = "STATUS_CHANGED"
    NOTE_ADDED = "NOTE_ADDED"
